name: Bot Andrey Mandiri 24 Jam

on:
  schedule:
    - cron: '*/30 * * * *' # Bot akan dicek setiap 30 menit agar tetap aktif
  workflow_dispatch: # Agar kamu bisa menyalakan manual kalau bot mati

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Ambil Kode dari GitHub
        uses: actions/checkout@v3

      - name: Siapkan Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Bahan Bot
        run: |
          pip install pyTelegramBotAPI requests flask

      - name: Jalankan Bot Andrey
        run: python main.py
